export const Theme = {
  colors: {
    primary: '#5E56E7',
    primaryLight: '#F8F7FF',
    background: '#FFFFFF',
    background2: '#f8f7ff',
    greyLight: '#F0F0F6',
    greyMedium: '#A0A0A0',
    greyDark: '#333333',
    white: '#FFFFFF',
    black: '#000000',
    success: '#10B981',
    redLight: '#FEE2E2',
    redMedium: '#FCA5A5',
    redDark: '#991B1B',
  },
  fonts: {
    regular: 'Montserrat-Regular',
    semiBold: 'Montserrat-SemiBold',
    medium: 'Montserrat-Regular',
  },
  spacing: {
    xs: 4,
    s: 6,
    sm: 8,
    m: 10,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
    huge: 40,
    giant: 50,
  },
  fontSizes: {
    xs: 12,
    sm: 14,
    md: 16,
    lg: 18,
    xl: 20,
    xxl: 24,
    title: 30,
    largeTitle: 32,
    hugeTitle: 48,
  },
};
